CREATE PROCEDURE GET_PRODUCT_LIST
AS
		SELECT * FROM Products AS PROD
		LEFT JOIN ProductPropertyBindings PB
		ON PROD.ID_PRODUCT_PRIMARY = PB.ID_PRODUCT_FOREIGN
		LEFT JOIN ProductTypes PT
		ON PT.ID_TYPE_PRIMARY = PROD.ID_TYPE_FOREIGN
		FOR JSON PATH;


