CREATE TABLE ProductTypes(
	ID_TYPE_PRIMARY INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NAME_TYPE NVARCHAR(50),
)

CREATE TABLE Products(
	ID_PRODUCT_PRIMARY INT PRIMARY KEY IDENTITY(1,1) NOT NULL, 
	ID_TYPE_FOREIGN INT UNIQUE NOT NULL,
	NAME_PRODUCT NVARCHAR(50),
	FOREIGN KEY (ID_TYPE_FOREIGN) REFERENCES ProductTypes(ID_TYPE_PRIMARY)
)

CREATE TABLE ProductPropertys(
	ID_PROPERY_PRIMARY INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	PROPERTYS NVARCHAR(MAX) NOT NULL
)

CREATE TABLE ProductPropertyBindings(
	ID_BINDING_PRIMRY INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ID_PRODUCT_FOREIGN INT NOT NULL,
	ID_PROPERTY_FOREIGN INT NOT NULL,
	FOREIGN KEY (ID_PRODUCT_FOREIGN) REFERENCES Products(ID_PRODUCT_PRIMARY),
	FOREIGN KEY (ID_PROPERTY_FOREIGN) REFERENCES ProductPropertys(ID_PROPERY_PRIMARY)
);
